# Generated by Django 2.2.7 on 2019-11-27 19:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0003_topic'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='topic',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='notes.Topic'),
        ),
    ]
