# Generated by Django 2.2.7 on 2019-11-27 22:15

from django.db import migrations
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0006_auto_20191127_2159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='topic',
            field=mptt.fields.TreeForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='notes.Topic'),
        ),
    ]
